title: Boleto Bancário - Código de Barras
email: boletobancario.contato@gmail.com
description: Gerador e Conversor de Boletos - Padrão Febraban
url: "https://boletobancario-codigodebarras.com"
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
